/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iel.atividade;

import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        tituloPeso = new javax.swing.JLabel();
        tituloAltura = new javax.swing.JLabel();
        textoPeso = new javax.swing.JTextField();
        textoAltura = new javax.swing.JTextField();
        botaoCalcular = new javax.swing.JButton();
        resultadooooo = new javax.swing.JLabel();
        fraserandom = new javax.swing.JLabel();
        resultadoNomenclatura = new javax.swing.JLabel();
        resultadoNum = new javax.swing.JLabel();
        nec = new javax.swing.JLabel();
        ideal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imc = new javax.swing.JLabel();
        imcName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        titulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titulo.setText("Super IMC Calc 2022");
        titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tituloPeso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tituloPeso.setText("Informe seu peso:");
        tituloPeso.setToolTipText("");
        tituloPeso.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tituloPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tituloAltura.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tituloAltura.setText("Informe sua altura:");
        tituloAltura.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        textoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPesoActionPerformed(evt);
            }
        });

        textoAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAlturaActionPerformed(evt);
            }
        });

        botaoCalcular.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        botaoCalcular.setText("CALCULAR");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        resultadooooo.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        resultadooooo.setText("Resultado:");

        fraserandom.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        fraserandom.setText("Você está");

        resultadoNomenclatura.setBackground(new java.awt.Color(255, 0, 204));
        resultadoNomenclatura.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        resultadoNomenclatura.setForeground(new java.awt.Color(0, 0, 0));
        resultadoNomenclatura.setText(" ");

        resultadoNum.setBackground(new java.awt.Color(153, 255, 51));
        resultadoNum.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resultadoNum.setForeground(new java.awt.Color(204, 0, 0));
        resultadoNum.setText(" ");

        nec.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ideal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ideal.setText(" ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Informe o peso (kg) apenas em números");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Informe a altura com ponto (ex 1.61)");

        imc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        imc.setText(" ");

        imcName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        imcName.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoCalcular)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imcName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nec, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ideal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultadooooo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultadoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fraserandom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoNomenclatura, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ideal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imcName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloPeso)
                            .addComponent(textoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloAltura)
                            .addComponent(textoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCalcular)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadooooo)
                    .addComponent(resultadoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fraserandom)
                    .addComponent(resultadoNomenclatura))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPesoActionPerformed
        
    }//GEN-LAST:event_textoPesoActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
       try {
           int ta = Integer.parseInt(textoPeso.getText());//peso
           float tb = Float.parseFloat(textoAltura.getText());//altura
           float sa = tb;//altura também
           float tr = (float)ta / (float)(tb*tb); //calculo IMC
           resultadoNum.setText(String.valueOf(tr)); //aparece na tela 
           
           
       if (tr < 18.5){

           //for para calcular peso ideal :)
           for (float tra = (float)0.0; (float)tra / (float)(sa*sa) < 18.8; tra+=1){
               float result = (float)tra / (float)(sa*sa);
               nec.setText(String.valueOf(tra));
               ideal.setText("Peso ideal APROX");
               imc.setText(String.valueOf(result));
               imcName.setText("IMC:");
               
           }
           
           resultadoNomenclatura.setText("Com Baixo Peso");
           JOptionPane.showMessageDialog(this, "Voce está com Baixo Peso", "Peso", WIDTH, null);
           
   
       } else if (tr > 18.5 && tr < 24.9){
           
           nec.setText("");
           ideal.setText("");
           imc.setText("");
           imcName.setText("");
           
           //normales não precisa de peso ideal
           resultadoNomenclatura.setText("Com Peso Saudável");
           JOptionPane.showMessageDialog(this, "Voce está com Peso Saudável", "Peso", WIDTH, null);
           
           
           
       } else if (tr > 25.0 && tr < 29.9) {
           
           for (float tra = (float)0.0; (float)tra / (float)(sa*sa) < 24.7; tra+=1){
               float result = (float)tra / (float)(sa*sa);
               nec.setText(String.valueOf(tra));
               ideal.setText("Peso ideal APROX");
               imc.setText(String.valueOf(result));
               imcName.setText("IMC:");
           }
           //peso ideal para gorditos
           resultadoNomenclatura.setText("Com Sobrepeso");
           JOptionPane.showMessageDialog(this, "Voce está com Sobrepeso", "Peso", WIDTH, null);
       } else if (tr > 30.0) {
           
           for (float tra = (float)0.0; (float)tra / (float)(sa*sa) < 24.7; tra+=1){
               float result = (float)tra / (float)(sa*sa);
               nec.setText(String.valueOf(tra));
               ideal.setText("Peso ideal APROX");
               imc.setText(String.valueOf(result));
               imcName.setText("IMC:");
           }
           //peso idel para gigante
           resultadoNomenclatura.setText("Obeso");
           JOptionPane.showMessageDialog(this, "Voce está Obeso", "Peso", WIDTH, null);
       }
           
       } catch (Exception e){
           JOptionPane.showMessageDialog(this, "Erro! Preencha as informações corretamente", "Erro", WIDTH, null);
       }
       
  
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void textoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAlturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JLabel fraserandom;
    private javax.swing.JLabel ideal;
    private javax.swing.JLabel imc;
    private javax.swing.JLabel imcName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nec;
    private javax.swing.JLabel resultadoNomenclatura;
    private javax.swing.JLabel resultadoNum;
    private javax.swing.JLabel resultadooooo;
    private javax.swing.JTextField textoAltura;
    private javax.swing.JTextField textoPeso;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloAltura;
    private javax.swing.JLabel tituloPeso;
    // End of variables declaration//GEN-END:variables
}
